Repository VoiceDeck/app, pull requests merged in 2024-01, with the labels that each got.

#3 Add pre-commit hook and CI check
  .editorconfig
  .github/workflows/check.yml
  .husky/pre-commit
  .lintstagedrc.json
  biome.json
  package.json
  pnpm-lock.yaml
Labels: config 🛠️

#8 feat: :sparkles: Add Error Boundary and custom Document component
  app/root.tsx
Labels: feature 🚀, config 🛠️

#7 config/add font and colors to tailwind
  app/root.tsx
  app/routes/_index.tsx
  app/tailwind.css
  package.json
  pnpm-lock.yaml
  tailwind.config.js
Labels: config 🛠️

#11 [README] Recommend direnv
  README.md
Labels: docs 📃

#10 feat: retrieve impact reports
  .github/workflows/test.yml
  README.md
  app/routes/impact-reports.tsx
  app/server/impactReportHelpers.test.ts
  app/server/impactReportHelpers.ts
  app/types/index.ts
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: feature 🚀

#12 Feat/install and style button
  app/components/ui/button.tsx
  package.json
  pnpm-lock.yaml
  tailwind.config.js
Labels: feature 🚀
