Repository VoiceDeck/app, pull requests merged in 2024-03, with the labels that each got.

#44 feat: update server to reflect latest funded amount
  app/directus.server.ts
  app/impact-reports.server.ts
  package.json
  pnpm-lock.yaml
Labels: feature 🚀

#42 Combine VoiceDeck with Intuition's Remix template fork
  .env.example
  .github/pull_request_template.md
  .gitignore
  README.md
  app/assets/intuition-logo.tsx
  app/assets/intuition-logotype.tsx
  app/components/account-button.tsx
  app/components/connect-button.tsx
  app/components/global/nav-menu.tsx
  app/components/header.tsx
  app/components/ui/dropdown-menu.tsx
  app/components/ui/multiple-selector.tsx
  app/components/ui/tooltip.tsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/lib/abis/ethMultiVault.ts
  app/lib/hooks/useGenericTxReducer.tsx
  app/lib/services/auth.server.ts
  app/lib/services/form.server.ts
  app/lib/services/session.server.ts
  app/lib/utils/auth-strategy.ts
  app/lib/utils/constants.ts
  app/lib/utils/misc.tsx
  app/lib/utils/nonce-provider.ts
  app/lib/utils/siwe.ts
  app/lib/utils/viem.ts
  app/root.tsx
  app/routes/_index.tsx
  app/routes/actions+/auth+/logout.tsx
  app/routes/login.tsx
  app/routes/profile+/$address+/index.tsx
  app/routes/profile+/$address+/route.tsx
  app/routes/profile+/$address+/settings.tsx
  app/routes/profile+/index.tsx
  app/routes/reports+/$slug.tsx
  app/routes/reports+/_index.tsx
  app/routes/reports+/route.tsx
  biome.json
  components.json
  env.d.ts
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  remix.env.d.ts
  src/images/app-template-logo.png
  src/images/template-badge.png
  tailwind.config.ts
  tsconfig.json
  types/user.ts
  vite.config.ts
Labels: feature 🚀

#46 feat: add server functionalities
  lib/directus.ts
  types/index.ts
Labels: feature 🚀

#40 feat: fetch a marketplace order linked to an impact report
  lib/impact-reports.ts
  lib/marketplace.ts
  package.json
  pnpm-lock.yaml
  types/index.ts
Labels: feature 🚀

#49 fix(api/reports/[slug]/route.ts,-reports/[slug]/page.tsx):
  app/api/reports/[slug]/route.ts
  app/reports/[slug]/page.tsx
Labels: feature 🚀

#52 Refactor/report-filters
  .lintstagedrc.json
  app/reports/page.tsx
  biome.json
  components/report-details/report-sidebar.tsx
  components/reports/filter-sidebar.tsx
  components/reports/outlet-combobox.tsx
  components/reports/report-card.tsx
  components/reports/reports-filters.tsx
  components/reports/reports-header.tsx
  components/reports/reports-view.tsx
  components/reports/states-combobox.tsx
  components/reports/voicedeck-stats.tsx
  components/ui/command.tsx
  components/ui/multiple-selector.tsx
  components/ui/popover.tsx
  components/ui/select.tsx
  contexts/filter.tsx
  lib/search-filter-utils.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  types/index.ts
Labels: feature 🚀

#41 Feat/show selected reports
  .lintstagedrc.json
  app/reports/page.tsx
  biome.json
  components/global/footer.tsx
  components/report-details/report-sidebar.tsx
  components/report-details/support/dialog.tsx
  components/report-details/support/form.tsx
  components/report-details/support/transaction-status.tsx
  components/reports/filter-sidebar.tsx
  components/reports/outlet-combobox.tsx
  components/reports/report-card.tsx
  components/reports/reports-filters.tsx
  components/reports/reports-header.tsx
  components/reports/reports-view.tsx
  components/reports/states-combobox.tsx
  components/reports/voicedeck-stats.tsx
  components/ui/command.tsx
  components/ui/label.tsx
  components/ui/multiple-selector.tsx
  components/ui/popover.tsx
  components/ui/select.tsx
  components/ui/slider.tsx
  components/ui/switch.tsx
  components/ui/textarea.tsx
  contexts/filter.tsx
  hooks/use-pagination.tsx
  hooks/use-support-form.ts
  lib/search-filter-utils.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/hero_img.jpg
  public/hero_imgLG.jpg
  public/reports_not_found.svg
  tsconfig.json
  types/index.ts
Labels: feature 🚀

#53 feat(settings-page,-global-nav):
  app/profile/[address]/page.tsx
  app/profile/[address]/settings/page.tsx
  components/global/connect-button.tsx
  components/global/footer.tsx
  components/global/nav-menu.tsx
  components/global/wallet-profile.tsx
  components/my-actions/summary.tsx
  components/report-details/support/dialog.tsx
  components/report-details/support/form.tsx
  components/reports/voicedeck-stats.tsx
  components/settings/user-info.tsx
  components/settings/verified-citizen.tsx
  components/settings/verified-status.tsx
  components/ui/command.tsx
  components/ui/popover.tsx
  components/ui/separator.tsx
  components/ui/slider.tsx
  pnpm-lock.yaml
Labels: feature 🚀

#58 Fix/summary data
  app/favicon.ico
  app/profile/[address]/page.tsx
  components/global/nav-links.tsx
  components/my-actions/history.tsx
  components/my-actions/summary.tsx
  components/profile/history-card.tsx
  components/profile/history.tsx
  components/profile/sidebar.tsx
  components/profile/summary.tsx
  config/site.ts
  lib/utils.ts
Labels: bug 🐛

#59 Fix/widescreen-adaptation
  app/layout.tsx
  app/reports/[slug]/page.tsx
  app/reports/page.tsx
  components/global/footer.tsx
  components/global/nav-links.tsx
  components/global/nav-menu.tsx
  components/global/wallet-profile.tsx
  components/reports/filter-sidebar.tsx
  components/reports/reports-filters.tsx
  components/reports/reports-header.tsx
  components/reports/reports-view.tsx
  components/ui/dynamic-category-icon.tsx
  contexts/filter.tsx
  lib/search-filter-utils.ts
Labels: feature 🚀

#64 Add pagination and display number of results
  components/reports/report-card.tsx
  components/reports/reports-view.tsx
  lib/search-filter-utils.ts
Labels: feature 🚀

#66 Patch 1.0.1
  app/favicon.ico
  app/layout.tsx
  app/reports/[slug]/page.tsx
  app/reports/page.tsx
  components/global/footer.tsx
  components/global/nav-links.tsx
  components/global/nav-menu.tsx
  components/global/wallet-profile.tsx
  components/profile/sidebar.tsx
  components/report-details/funding-progress.tsx
  components/report-details/report-sidebar.tsx
  components/report-details/report-support-feed.tsx
  components/report-details/support/dialog.tsx
  components/report-details/support/form.tsx
  components/report-details/support/transaction-status.tsx
  components/reports/filter-sidebar.tsx
  components/reports/report-card.tsx
  components/reports/reports-filters.tsx
  components/reports/reports-header.tsx
  components/reports/reports-view.tsx
  components/settings/user-info.tsx
  components/ui/alert.tsx
  components/ui/dynamic-category-icon.tsx
  config/site.ts
  config/wagmi.ts
  contexts/filter.tsx
  contexts/wagmi.tsx
  hooks/use-buy-fraction.ts
  hooks/use-get-current-erc20-allowance.ts
  hooks/use-media-query.ts
  hooks/use-pagination.ts
  hooks/use-support-form.ts
  lib/impact-reports.ts
  lib/marketplace.ts
  lib/search-filter-utils.ts
  lib/utils.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/opengraph-image.png
  public/vercel.svg
  tsconfig.json
Labels: feature 🚀

#75 Fix home component redirect and adapt reports view layout
  app/page.tsx
  app/profile/[address]/page.tsx
  app/profile/[address]/settings/page.tsx
  components/reports/reports-view.tsx
  components/reports/voicedeck-stats.tsx
  components/settings/user-info.tsx
  components/settings/verified-citizen.tsx
  components/settings/verified-status.tsx
Labels: bug 🐛, feature 🚀
